application: sean-mulligan
version: 1
runtime: go
api_version: go1

handlers:
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html
- url: /static
  static_dir: static
- url: /.*
  static_dir: static
  #script: _go_app
- url: /
  static_dir: static
